# Generated by Django 5.2.6 on 2025-09-06 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('name ', 'Name'), ('price ', 'Price '), ('description ', 'Description '), ('thumbnail ', 'Thumbnail '), ('category', 'Category'), ('is_featured', 'Is_Featured'), ('brand', 'Brand')], max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
                ('brand', models.CharField(max_length=100)),
            ],
        ),
    ]
