# Generated by Django 5.2.6 on 2025-09-18 14:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('JERSEY', 'Jersey'), ('SHOES', 'Sepatu Bola'), ('BALL', 'Bola'), ('BOTTLE', 'botol'), ('TRAINING KIT', 'Pakaian Latihan')], max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
                ('brand', models.CharField(max_length=100)),
            ],
        ),
    ]
